### ISSUE TITLE
GUI Progressbar and Progress Reporting

### ISSUE THREAD

**Issue by alexanderlanganke** [alexanderlanganke/ocrmypdfgui#2]
Use the get_progressbar_class of ocrmypdf and integrate into GUI.

**Comment by alexanderlanganke** [comment]
Progressbar for batch processing is implemented.
Progressbar for single File remains todo.

**Comment by Nexfia** [comment]
> 实施批处理进度栏。
> 单个文件的进度栏仍有待解决。
Translate by Google Translate:
ocrmypdf uses the tqdm module to output progress information. If you want to get the progress information recognized by the OCR of a single file from tqdm, you can find a tqdm class in the std.py file of the tqdm module, which has a format_meter method, and there is a variable named format_dict in the method, which contains Processing progress information.
原文：
ocrmypdf使用了tqdm模块来输出进度信息。如果你想从tqdm中获取单个文件OCR识别的进度信息，你可以在tqdm模块的std.py文件中找到一个tqdm类，里面有一个format_meter方法，方法里面有个名字是format_dict的变量，它包含了处理进度的信息。

**Comment by Nexfia** [comment]
![截图_选择区域_20210509205304](https://user-images.githubusercontent.com/65474621/117573278-93f41100-b109-11eb-8d93-f3bdf11661ab.png)
Translate by Google Translate:
The attributes of'desc','n', and'total' inside are worthy of our attention.
n: Number of finished iterations.
total: The expected total number of iterations. If meaningless (None), only basic progress statistics are displayed (no ETA).
desc: The steps being executed. For example: PDF/A conversion, OCR, Scanning contents

原文：
里面的 'desc'、'n'、'total' 属性是值得我们去注意的。
n：Number of finished iterations.
total：The expected total number of iterations. If meaningless (None),only basic progress statistics are displayed (no ETA).
desc：正在执行的步骤。比如：PDF/A conversion、OCR、Scanning contents

**Comment by alexanderlanganke** [comment]
I am now at the same point you are I believe..

My callback function is bound to the plugin and not to the Main Window.

**Comment by alexanderlanganke** [comment]
I have it working on my progressbar branch. Take a Look if you are still working on this.
