### ISSUE TITLE
Folder names are not shown

### ISSUE THREAD

**Issue by marreromarco** [alexanderlanganke/ocrmypdfgui#22]
I would like to point out to a minor issue happening on Manjaro Linux KDE (latest):

![2021-08-26_14-39](https://user-images.githubusercontent.com/58692066/131018240-3b523166-7a96-4718-aaa2-eacbd5b2e105.png)

In order to show the names of folders, it is necessary to click over them instead of the name appearing automatically.

Thank you very much for your hard work ! I hope the suggestion would be useful...

**Comment by alexanderlanganke** [comment]
Build failed.. will look at that when I have the time

**Comment by marreromarco** [comment]
After updating Manjaro today, the issue has been solved !

 Might have been an OS specific issue or KDE related. 

**Thanks for your kind help!** Your GUI has been a life saver !

**Comment by alexanderlanganke** [comment]
Glad your enjoying it and that the issue is resolved.

I actually did not expect anybody else to use the GUI and packaged it as a
snap just to see if I could get it to work.

Feel free to open an issue on GitHub if you find something new or have a
suggestion for an enhancement.
