### ISSUE TITLE
How to install without snap?

### ISSUE THREAD

**Issue by aggsol** [alexanderlanganke/ocrmypdfgui#26]
I tried
```
pip install --user ocrmypdfgui
```
but when I start it then I get the following error:

```
ocrmypdfgui/gui.py", line 12, in <module>
    from tkinter import *
ModuleNotFoundError: No module named 'tkinter'
```
Is there another way?

P.S.: You tool is mentioned in the current issue of the c't magazine:

https://www.heise.de/select/ct/2022/1/2128513571512028755

**Comment by aggsol** [comment]
Hi!

Ich habe es gelöst: `sudo apt install python3-tk`

Man könnte das in die Readme aufnehmen.

Der Artikel ist vielleicht mal auch so auf heise.de zu lesen. Sobald meine Printausgabe da ist, schicke ich dir (wie?) einen Scan. :-)

**Comment by alexanderlanganke** [comment]
Heft zufällig schon bekommen?

**Comment by aggsol** [comment]
Wie kann ich dir eine Email schicken?

**Comment by alexanderlanganke** [comment]
Gern an ***@***.***

Danke!

P.s. die PIP Version des Programmes habe ich weiter entwickelt. Die benutzt
jetzt gtk3 und ist deutlich hübscher.

Ggf. Neu installieren via pip install ocrmypdfgui. Update geht nicht meine
ich
