### ISSUE TITLE
I can not run the ocrmypdfgui.py.It did not find the settings.ini.

### ISSUE THREAD

**Issue by Nexfia** [alexanderlanganke/ocrmypdfgui#3]
![image](https://user-images.githubusercontent.com/65474621/117403543-ecc17f00-af3a-11eb-8373-eac408830ad2.png)

I can not run the ocrmypdfgui.py.
Beaacuse it did not find the settings.ini.

**Comment by alexanderlanganke** [comment]
Hi there!
Thanks for trying out my little project.

You are obviously correct. I am currently working on the settings part and am researching dynamic APIs. I am thinking about using the "signature" module to implement the UI without hardcoding it.
settings.ini is a placeholder for persistent settings the user will be able to save.

I pushed my placeholder settings.ini to main branch. Using this you should be able to run the program.
Currently the OCR options are locked to deskew=true, clean=true and lang=eng+deu. I will make this dynamic as this project progresses.

**Comment by alexanderlanganke** [comment]
Settings functionality is now implemented.
